/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.hciproject;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author jagjeet
 */
public class HciProject extends javax.swing.JFrame {

    /**
     * Creates new form HciProject
     */
    public HciProject() {
        initComponents();
                
warning.setVisible(false); 
leftindicator.setVisible(false);
rightindicator.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rightindicator = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        leftindicator = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        warning = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Warning");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1671, 70, 160, 80));

        jButton2.setText("Left Indicator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 190, 160, 80));

        jButton3.setText("Right Indicator");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 300, 160, 80));

        rightindicator.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/hciproject/rrightindicator.jpg"))); // NOI18N

        javax.swing.GroupLayout rightindicatorLayout = new javax.swing.GroupLayout(rightindicator);
        rightindicator.setLayout(rightindicatorLayout);
        rightindicatorLayout.setHorizontalGroup(
            rightindicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );
        rightindicatorLayout.setVerticalGroup(
            rightindicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );

        getContentPane().add(rightindicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        leftindicator.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/hciproject/rleftindicator.jpg"))); // NOI18N

        javax.swing.GroupLayout leftindicatorLayout = new javax.swing.GroupLayout(leftindicator);
        leftindicator.setLayout(leftindicatorLayout);
        leftindicatorLayout.setHorizontalGroup(
            leftindicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftindicatorLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(106, 106, 106))
        );
        leftindicatorLayout.setVerticalGroup(
            leftindicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        getContentPane().add(leftindicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        warning.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/hciproject/rwarning.jpg"))); // NOI18N

        javax.swing.GroupLayout warningLayout = new javax.swing.GroupLayout(warning);
        warning.setLayout(warningLayout);
        warningLayout.setHorizontalGroup(
            warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2480, 2480, 2480))
        );
        warningLayout.setVerticalGroup(
            warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 1920, 1120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/hciproject/final1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
warning.setVisible(true); 

leftindicator.setVisible(false);
rightindicator.setVisible(false);

InputStream in;
         try{
             in =new FileInputStream(new File ("/home/jagjeet/NetBeansProjects/HCI/src/my/hciproject/School_Fire_Alarm-Cullen_Card-202875844 (mp3cut.net).wav"));
             
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             
         }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     leftindicator.setVisible(true); 
     warning.setVisible(false); 

rightindicator.setVisible(false);
 
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      rightindicator.setVisible(true);
      warning.setVisible(false); 
leftindicator.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HciProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HciProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HciProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HciProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HciProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel leftindicator;
    private javax.swing.JPanel rightindicator;
    private javax.swing.JPanel warning;
    // End of variables declaration//GEN-END:variables
}
